### ISSUE TITLE
LOGIN INFORMATION

### ISSUE THREAD

**Issue by Romanrifle** [jorexdeveloper/termux-nethunter#11]
~ $ nh
localhost login: root
Password: root

Login incorrect

~ $ nh
localhost login: kali
Password: kali

Login incorrect

**Comment by jorexdeveloper** [comment]
> ~ $ nh localhost login: root Password: root
> 
> Login incorrect
> 
> ~ $ nh localhost login: kali Password: kali
> 
> Login incorrect

Will fix this later...
for now, execute below commands to change password.

To Login as root

```bash
~$ nh --command='bash -l'
```

To change password, use the command `passwd`.

```bash
~# passwd -h
Usage: passwd [options] [LOGIN]

Options:
  -a, --all                     report password status on all accounts
  -d, --delete                  delete the password for the named account
  -e, --expire                  force expire the password for the named account
  -h, --help                    display this help message and exit
  -k, --keep-tokens             change password only if expired
  -i, --inactive INACTIVE       set password inactive after expiration
                                to INACTIVE
  -l, --lock                    lock the password of the named account
  -n, --mindays MIN_DAYS        set minimum number of days before password
                                change to MIN_DAYS
  -q, --quiet                   quiet mode
  -r, --repository REPOSITORY   change password in REPOSITORY repository
  -R, --root CHROOT_DIR         directory to chroot into
  -S, --status                  report password status on the named account
  -u, --unlock                  unlock the password of the named account
  -w, --warndays WARN_DAYS      set expiration warning days to WARN_DAYS
  -x, --maxdays MAX_DAYS        set maximum number of days before password
                                change to MAX_DAYS
```

Change password for **kali**

```bash
~# passwd kali
```

**Comment by jorexdeveloper** [comment]
However, you must provide more info to proceed with this issue. Everything seems fine.

**Comment by Romanrifle** [comment]
~# passwd -d kali Worked like Magic Thanks a bunch

**Comment by Heath41** [comment]
Login incorrect
localhost login: kali
Password:kali
A valid context for kali could not be obtained.

Cannot make/remove an entry for the specified session
~ $
Please help me

**Comment by Heath41** [comment]
Every time i type kali in local host login and kali in password this issue above apears

**Comment by jorexdeveloper** [comment]
> Every time i type kali in local host login and kali in password this issue above apears

Try [this](https://github.com/jorexdeveloper/termux-nethunter/issues/11#issuecomment-2406579065)

**Comment by Heath41** [comment]
Am not a root user sir

**Comment by Heath41** [comment]
It didn't work

**Comment by Heath41** [comment]
~ $ nh
localhost login: kali
Password:
A valid context for kali could not be obtained.
                                                      Cannot make/remove an entry for the specified session
~ $

**Comment by Heath41** [comment]
Dude i tried every script it didn't work help me man comon i will be really greatfull

**Comment by jorexdeveloper** [comment]
I can only solve your problem, if i know what it is or what is causing it.

In that case, I am going to assume you **succesfuly** installed the rootfs with no problems. (Highly recommend that you re-install the whole rootfs and allow it to complete with no errors)

Assuming everything up to installation worked fine, then the problem is with the password input.

So, you shall login into the rootfs as **root user** (no need to have root access in termux, this is just a simulated root evironment.)

Then delete the password for **kali**.

Steps are [here](https://github.com/jorexdeveloper/termux-nethunter/issues/11#issuecomment-2406579065)

Confirm that the password for kali is deleted and try logging in again.

If this doesn't work, then I shall need further info to help you. i.e

- Scereenshots of succesful installation.
- Screenshots of login failure.
