### ISSUE TITLE
vnc

### ISSUE THREAD

**Issue by Ahmadtaufik731** [jorexdeveloper/termux-nethunter#7]
note open vncserver in realvnc
vnc not matching 
vnc -list vnc not add id list for vnc

solusi work for me 

tigervncserver -xstartup /usr/bin/startxfce4

to open vnc server

**Comment by jorexdeveloper** [comment]
@Ahmadtaufik731

I have connected to **Real VNC** using the vnc wrapper and it seemed to work fine.

I think you **forgot to include the correct port** in the address.
The address should look something like

```bash
localhost:5900
```
For **root** user

and

```bash
localhost:5901
```

for user **Kali**

The reason `tigervncserver -xstartup /usr/bin/startxfce4` worked is because it starts the VNC server at port `5900` and **Real VNC** also defaults to the same port if none is supplied.
